#BNF+IAT 1.0 UTF-8;
!grammar zgty;
!slot <contact>;
!slot <callPre>;
!slot <callTo>;
!start <callStart>;
<callStart>:[<callPre>][<callTo>]<contact>;
<contact>:是|不是|打卡|符实|陈威|赵博睿|王晓迪|袁彤|黄浩|关红兵|刘超超|安立|杨周群|付文正|魏鑫|宋丽|王伯韬|胡康健|巫志英|王国庆|刘志征|隋丽娟|沙蓉|王莹|王颖|芮佳|陈洁|潘丽华|龙辉|刘芳|宋薇|陈静怡|王华|李佳|孙素珍|陈楠|王运河|王威|陈阳|刘方方|贺容|陶松|周泽毅|刘前进|尹若惜|谭锦麟|严斌|孙铮|杨榕桦|王高胜|周青波|陈正勇|崔节敏|何伟|张闯|杨彪|邢保华|戴毅毅|吕云龙|邓楠|王华峰|赵华|胡中云|高春华|陈傲|刘贺|李卫|陈胜利|陈亮|赵德乾|王柱波|李东坡|齐越|李攀|邢金勇|刘永腾|黄忠明|雷鹏|王倩|潘镇宇|程凯文|张佳楠|张忠平|杨猛|牛鹏举|刘铮铮|彭坤|张善清|陈硕|刘露|赵宏宇|詹畅宇|吴志远|唐为|田勇|胡济阳|田飞龙|吴还有|宋洪进|杨代键|何凡|唐道善|马博|张自彬|梅泷艺|雷文明|邓昆|丁辉|黄银|刘骜|马尧|谢睿|刘洁|范时剑|鄢来明|聂煜|周鑫泉|钱潇|张向阳|张东奎|刘星|左剑|陈馨荥|王鸿|尹世才|何鹏|马瑞鹏|冉建军|王亮亮|王胜|刘明亮|陶泽民|郭松洋|王志帮|张龙兵|李阳|王岳飞|赵佳伟|张元健|朱金磊|曾伟|刘昌顺|任磊|舒俊杰|严小龙|薛斐|邢丰|叶光宇|杜宇|王海龙|王瑞刚|张旭;
<callPre>:我要|我想|我想要|我|重新;
<callTo>:找|寻找|联系;
