package com.zgty.oarobot.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VISITOR".
*/
public class VisitorDao extends AbstractDao<Visitor, String> {

    public static final String TABLENAME = "VISITOR";

    /**
     * Properties of entity Visitor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Visit_id = new Property(1, String.class, "visit_id", false, "VISIT_ID");
        public final static Property Time = new Property(2, String.class, "time", false, "TIME");
        public final static Property Infos = new Property(3, String.class, "infos", false, "INFOS");
    }


    public VisitorDao(DaoConfig config) {
        super(config);
    }
    
    public VisitorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VISITOR\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"VISIT_ID\" TEXT," + // 1: visit_id
                "\"TIME\" TEXT," + // 2: time
                "\"INFOS\" TEXT);"); // 3: infos
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VISITOR\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Visitor entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String visit_id = entity.getVisit_id();
        if (visit_id != null) {
            stmt.bindString(2, visit_id);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(3, time);
        }
 
        String infos = entity.getInfos();
        if (infos != null) {
            stmt.bindString(4, infos);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Visitor entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String visit_id = entity.getVisit_id();
        if (visit_id != null) {
            stmt.bindString(2, visit_id);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(3, time);
        }
 
        String infos = entity.getInfos();
        if (infos != null) {
            stmt.bindString(4, infos);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Visitor readEntity(Cursor cursor, int offset) {
        Visitor entity = new Visitor( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // visit_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // time
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // infos
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Visitor entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setVisit_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setInfos(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Visitor entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(Visitor entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Visitor entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
