package com.zgty.oarobot.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WORK_ON_OFF".
*/
public class WorkOnOffDao extends AbstractDao<WorkOnOff, String> {

    public static final String TABLENAME = "WORK_ON_OFF";

    /**
     * Properties of entity WorkOnOff.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Id_clerk = new Property(2, String.class, "id_clerk", false, "ID_CLERK");
        public final static Property Work_on1 = new Property(3, String.class, "work_on1", false, "WORK_ON1");
        public final static Property Work_off1 = new Property(4, String.class, "work_off1", false, "WORK_OFF1");
        public final static Property Work_on2 = new Property(5, String.class, "work_on2", false, "WORK_ON2");
        public final static Property Work_off2 = new Property(6, String.class, "work_off2", false, "WORK_OFF2");
        public final static Property Work_on3 = new Property(7, String.class, "work_on3", false, "WORK_ON3");
        public final static Property Work_off3 = new Property(8, String.class, "work_off3", false, "WORK_OFF3");
        public final static Property Work_on4 = new Property(9, String.class, "work_on4", false, "WORK_ON4");
        public final static Property Work_off4 = new Property(10, String.class, "work_off4", false, "WORK_OFF4");
        public final static Property Work_on5 = new Property(11, String.class, "work_on5", false, "WORK_ON5");
        public final static Property Work_off5 = new Property(12, String.class, "work_off5", false, "WORK_OFF5");
        public final static Property Work_on6 = new Property(13, String.class, "work_on6", false, "WORK_ON6");
        public final static Property Work_off6 = new Property(14, String.class, "work_off6", false, "WORK_OFF6");
        public final static Property Work_on7 = new Property(15, String.class, "work_on7", false, "WORK_ON7");
        public final static Property Work_off7 = new Property(16, String.class, "work_off7", false, "WORK_OFF7");
        public final static Property Work_on8 = new Property(17, String.class, "work_on8", false, "WORK_ON8");
        public final static Property Work_off8 = new Property(18, String.class, "work_off8", false, "WORK_OFF8");
        public final static Property Work_on9 = new Property(19, String.class, "work_on9", false, "WORK_ON9");
        public final static Property Work_off9 = new Property(20, String.class, "work_off9", false, "WORK_OFF9");
        public final static Property Work_on10 = new Property(21, String.class, "work_on10", false, "WORK_ON10");
        public final static Property Work_off10 = new Property(22, String.class, "work_off10", false, "WORK_OFF10");
        public final static Property Work_on11 = new Property(23, String.class, "work_on11", false, "WORK_ON11");
        public final static Property Work_off11 = new Property(24, String.class, "work_off11", false, "WORK_OFF11");
        public final static Property Work_on12 = new Property(25, String.class, "work_on12", false, "WORK_ON12");
        public final static Property Work_off12 = new Property(26, String.class, "work_off12", false, "WORK_OFF12");
        public final static Property Work_on13 = new Property(27, String.class, "work_on13", false, "WORK_ON13");
        public final static Property Work_off13 = new Property(28, String.class, "work_off13", false, "WORK_OFF13");
        public final static Property Work_on14 = new Property(29, String.class, "work_on14", false, "WORK_ON14");
        public final static Property Work_off14 = new Property(30, String.class, "work_off14", false, "WORK_OFF14");
        public final static Property Work_on15 = new Property(31, String.class, "work_on15", false, "WORK_ON15");
        public final static Property Work_off15 = new Property(32, String.class, "work_off15", false, "WORK_OFF15");
        public final static Property Work_on16 = new Property(33, String.class, "work_on16", false, "WORK_ON16");
        public final static Property Work_off16 = new Property(34, String.class, "work_off16", false, "WORK_OFF16");
        public final static Property Work_on17 = new Property(35, String.class, "work_on17", false, "WORK_ON17");
        public final static Property Work_off17 = new Property(36, String.class, "work_off17", false, "WORK_OFF17");
        public final static Property Work_on18 = new Property(37, String.class, "work_on18", false, "WORK_ON18");
        public final static Property Work_off18 = new Property(38, String.class, "work_off18", false, "WORK_OFF18");
        public final static Property Work_on19 = new Property(39, String.class, "work_on19", false, "WORK_ON19");
        public final static Property Work_off19 = new Property(40, String.class, "work_off19", false, "WORK_OFF19");
        public final static Property Work_on20 = new Property(41, String.class, "work_on20", false, "WORK_ON20");
        public final static Property Work_off20 = new Property(42, String.class, "work_off20", false, "WORK_OFF20");
        public final static Property Work_on21 = new Property(43, String.class, "work_on21", false, "WORK_ON21");
        public final static Property Work_off21 = new Property(44, String.class, "work_off21", false, "WORK_OFF21");
        public final static Property Work_on22 = new Property(45, String.class, "work_on22", false, "WORK_ON22");
        public final static Property Work_off22 = new Property(46, String.class, "work_off22", false, "WORK_OFF22");
        public final static Property Work_on23 = new Property(47, String.class, "work_on23", false, "WORK_ON23");
        public final static Property Work_off23 = new Property(48, String.class, "work_off23", false, "WORK_OFF23");
        public final static Property Work_on24 = new Property(49, String.class, "work_on24", false, "WORK_ON24");
        public final static Property Work_off24 = new Property(50, String.class, "work_off24", false, "WORK_OFF24");
        public final static Property Work_on25 = new Property(51, String.class, "work_on25", false, "WORK_ON25");
        public final static Property Work_off25 = new Property(52, String.class, "work_off25", false, "WORK_OFF25");
        public final static Property Work_on26 = new Property(53, String.class, "work_on26", false, "WORK_ON26");
        public final static Property Work_off26 = new Property(54, String.class, "work_off26", false, "WORK_OFF26");
        public final static Property Work_on27 = new Property(55, String.class, "work_on27", false, "WORK_ON27");
        public final static Property Work_off27 = new Property(56, String.class, "work_off27", false, "WORK_OFF27");
        public final static Property Work_on28 = new Property(57, String.class, "work_on28", false, "WORK_ON28");
        public final static Property Work_off28 = new Property(58, String.class, "work_off28", false, "WORK_OFF28");
        public final static Property Work_on29 = new Property(59, String.class, "work_on29", false, "WORK_ON29");
        public final static Property Work_off29 = new Property(60, String.class, "work_off29", false, "WORK_OFF29");
        public final static Property Work_on30 = new Property(61, String.class, "work_on30", false, "WORK_ON30");
        public final static Property Work_off30 = new Property(62, String.class, "work_off30", false, "WORK_OFF30");
        public final static Property Work_on31 = new Property(63, String.class, "work_on31", false, "WORK_ON31");
        public final static Property Work_off31 = new Property(64, String.class, "work_off31", false, "WORK_OFF31");
        public final static Property Mark_all = new Property(65, String.class, "mark_all", false, "MARK_ALL");
    }


    public WorkOnOffDao(DaoConfig config) {
        super(config);
    }
    
    public WorkOnOffDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WORK_ON_OFF\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"ID_CLERK\" TEXT," + // 2: id_clerk
                "\"WORK_ON1\" TEXT," + // 3: work_on1
                "\"WORK_OFF1\" TEXT," + // 4: work_off1
                "\"WORK_ON2\" TEXT," + // 5: work_on2
                "\"WORK_OFF2\" TEXT," + // 6: work_off2
                "\"WORK_ON3\" TEXT," + // 7: work_on3
                "\"WORK_OFF3\" TEXT," + // 8: work_off3
                "\"WORK_ON4\" TEXT," + // 9: work_on4
                "\"WORK_OFF4\" TEXT," + // 10: work_off4
                "\"WORK_ON5\" TEXT," + // 11: work_on5
                "\"WORK_OFF5\" TEXT," + // 12: work_off5
                "\"WORK_ON6\" TEXT," + // 13: work_on6
                "\"WORK_OFF6\" TEXT," + // 14: work_off6
                "\"WORK_ON7\" TEXT," + // 15: work_on7
                "\"WORK_OFF7\" TEXT," + // 16: work_off7
                "\"WORK_ON8\" TEXT," + // 17: work_on8
                "\"WORK_OFF8\" TEXT," + // 18: work_off8
                "\"WORK_ON9\" TEXT," + // 19: work_on9
                "\"WORK_OFF9\" TEXT," + // 20: work_off9
                "\"WORK_ON10\" TEXT," + // 21: work_on10
                "\"WORK_OFF10\" TEXT," + // 22: work_off10
                "\"WORK_ON11\" TEXT," + // 23: work_on11
                "\"WORK_OFF11\" TEXT," + // 24: work_off11
                "\"WORK_ON12\" TEXT," + // 25: work_on12
                "\"WORK_OFF12\" TEXT," + // 26: work_off12
                "\"WORK_ON13\" TEXT," + // 27: work_on13
                "\"WORK_OFF13\" TEXT," + // 28: work_off13
                "\"WORK_ON14\" TEXT," + // 29: work_on14
                "\"WORK_OFF14\" TEXT," + // 30: work_off14
                "\"WORK_ON15\" TEXT," + // 31: work_on15
                "\"WORK_OFF15\" TEXT," + // 32: work_off15
                "\"WORK_ON16\" TEXT," + // 33: work_on16
                "\"WORK_OFF16\" TEXT," + // 34: work_off16
                "\"WORK_ON17\" TEXT," + // 35: work_on17
                "\"WORK_OFF17\" TEXT," + // 36: work_off17
                "\"WORK_ON18\" TEXT," + // 37: work_on18
                "\"WORK_OFF18\" TEXT," + // 38: work_off18
                "\"WORK_ON19\" TEXT," + // 39: work_on19
                "\"WORK_OFF19\" TEXT," + // 40: work_off19
                "\"WORK_ON20\" TEXT," + // 41: work_on20
                "\"WORK_OFF20\" TEXT," + // 42: work_off20
                "\"WORK_ON21\" TEXT," + // 43: work_on21
                "\"WORK_OFF21\" TEXT," + // 44: work_off21
                "\"WORK_ON22\" TEXT," + // 45: work_on22
                "\"WORK_OFF22\" TEXT," + // 46: work_off22
                "\"WORK_ON23\" TEXT," + // 47: work_on23
                "\"WORK_OFF23\" TEXT," + // 48: work_off23
                "\"WORK_ON24\" TEXT," + // 49: work_on24
                "\"WORK_OFF24\" TEXT," + // 50: work_off24
                "\"WORK_ON25\" TEXT," + // 51: work_on25
                "\"WORK_OFF25\" TEXT," + // 52: work_off25
                "\"WORK_ON26\" TEXT," + // 53: work_on26
                "\"WORK_OFF26\" TEXT," + // 54: work_off26
                "\"WORK_ON27\" TEXT," + // 55: work_on27
                "\"WORK_OFF27\" TEXT," + // 56: work_off27
                "\"WORK_ON28\" TEXT," + // 57: work_on28
                "\"WORK_OFF28\" TEXT," + // 58: work_off28
                "\"WORK_ON29\" TEXT," + // 59: work_on29
                "\"WORK_OFF29\" TEXT," + // 60: work_off29
                "\"WORK_ON30\" TEXT," + // 61: work_on30
                "\"WORK_OFF30\" TEXT," + // 62: work_off30
                "\"WORK_ON31\" TEXT," + // 63: work_on31
                "\"WORK_OFF31\" TEXT," + // 64: work_off31
                "\"MARK_ALL\" TEXT);"); // 65: mark_all
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WORK_ON_OFF\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WorkOnOff entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String id_clerk = entity.getId_clerk();
        if (id_clerk != null) {
            stmt.bindString(3, id_clerk);
        }
 
        String work_on1 = entity.getWork_on1();
        if (work_on1 != null) {
            stmt.bindString(4, work_on1);
        }
 
        String work_off1 = entity.getWork_off1();
        if (work_off1 != null) {
            stmt.bindString(5, work_off1);
        }
 
        String work_on2 = entity.getWork_on2();
        if (work_on2 != null) {
            stmt.bindString(6, work_on2);
        }
 
        String work_off2 = entity.getWork_off2();
        if (work_off2 != null) {
            stmt.bindString(7, work_off2);
        }
 
        String work_on3 = entity.getWork_on3();
        if (work_on3 != null) {
            stmt.bindString(8, work_on3);
        }
 
        String work_off3 = entity.getWork_off3();
        if (work_off3 != null) {
            stmt.bindString(9, work_off3);
        }
 
        String work_on4 = entity.getWork_on4();
        if (work_on4 != null) {
            stmt.bindString(10, work_on4);
        }
 
        String work_off4 = entity.getWork_off4();
        if (work_off4 != null) {
            stmt.bindString(11, work_off4);
        }
 
        String work_on5 = entity.getWork_on5();
        if (work_on5 != null) {
            stmt.bindString(12, work_on5);
        }
 
        String work_off5 = entity.getWork_off5();
        if (work_off5 != null) {
            stmt.bindString(13, work_off5);
        }
 
        String work_on6 = entity.getWork_on6();
        if (work_on6 != null) {
            stmt.bindString(14, work_on6);
        }
 
        String work_off6 = entity.getWork_off6();
        if (work_off6 != null) {
            stmt.bindString(15, work_off6);
        }
 
        String work_on7 = entity.getWork_on7();
        if (work_on7 != null) {
            stmt.bindString(16, work_on7);
        }
 
        String work_off7 = entity.getWork_off7();
        if (work_off7 != null) {
            stmt.bindString(17, work_off7);
        }
 
        String work_on8 = entity.getWork_on8();
        if (work_on8 != null) {
            stmt.bindString(18, work_on8);
        }
 
        String work_off8 = entity.getWork_off8();
        if (work_off8 != null) {
            stmt.bindString(19, work_off8);
        }
 
        String work_on9 = entity.getWork_on9();
        if (work_on9 != null) {
            stmt.bindString(20, work_on9);
        }
 
        String work_off9 = entity.getWork_off9();
        if (work_off9 != null) {
            stmt.bindString(21, work_off9);
        }
 
        String work_on10 = entity.getWork_on10();
        if (work_on10 != null) {
            stmt.bindString(22, work_on10);
        }
 
        String work_off10 = entity.getWork_off10();
        if (work_off10 != null) {
            stmt.bindString(23, work_off10);
        }
 
        String work_on11 = entity.getWork_on11();
        if (work_on11 != null) {
            stmt.bindString(24, work_on11);
        }
 
        String work_off11 = entity.getWork_off11();
        if (work_off11 != null) {
            stmt.bindString(25, work_off11);
        }
 
        String work_on12 = entity.getWork_on12();
        if (work_on12 != null) {
            stmt.bindString(26, work_on12);
        }
 
        String work_off12 = entity.getWork_off12();
        if (work_off12 != null) {
            stmt.bindString(27, work_off12);
        }
 
        String work_on13 = entity.getWork_on13();
        if (work_on13 != null) {
            stmt.bindString(28, work_on13);
        }
 
        String work_off13 = entity.getWork_off13();
        if (work_off13 != null) {
            stmt.bindString(29, work_off13);
        }
 
        String work_on14 = entity.getWork_on14();
        if (work_on14 != null) {
            stmt.bindString(30, work_on14);
        }
 
        String work_off14 = entity.getWork_off14();
        if (work_off14 != null) {
            stmt.bindString(31, work_off14);
        }
 
        String work_on15 = entity.getWork_on15();
        if (work_on15 != null) {
            stmt.bindString(32, work_on15);
        }
 
        String work_off15 = entity.getWork_off15();
        if (work_off15 != null) {
            stmt.bindString(33, work_off15);
        }
 
        String work_on16 = entity.getWork_on16();
        if (work_on16 != null) {
            stmt.bindString(34, work_on16);
        }
 
        String work_off16 = entity.getWork_off16();
        if (work_off16 != null) {
            stmt.bindString(35, work_off16);
        }
 
        String work_on17 = entity.getWork_on17();
        if (work_on17 != null) {
            stmt.bindString(36, work_on17);
        }
 
        String work_off17 = entity.getWork_off17();
        if (work_off17 != null) {
            stmt.bindString(37, work_off17);
        }
 
        String work_on18 = entity.getWork_on18();
        if (work_on18 != null) {
            stmt.bindString(38, work_on18);
        }
 
        String work_off18 = entity.getWork_off18();
        if (work_off18 != null) {
            stmt.bindString(39, work_off18);
        }
 
        String work_on19 = entity.getWork_on19();
        if (work_on19 != null) {
            stmt.bindString(40, work_on19);
        }
 
        String work_off19 = entity.getWork_off19();
        if (work_off19 != null) {
            stmt.bindString(41, work_off19);
        }
 
        String work_on20 = entity.getWork_on20();
        if (work_on20 != null) {
            stmt.bindString(42, work_on20);
        }
 
        String work_off20 = entity.getWork_off20();
        if (work_off20 != null) {
            stmt.bindString(43, work_off20);
        }
 
        String work_on21 = entity.getWork_on21();
        if (work_on21 != null) {
            stmt.bindString(44, work_on21);
        }
 
        String work_off21 = entity.getWork_off21();
        if (work_off21 != null) {
            stmt.bindString(45, work_off21);
        }
 
        String work_on22 = entity.getWork_on22();
        if (work_on22 != null) {
            stmt.bindString(46, work_on22);
        }
 
        String work_off22 = entity.getWork_off22();
        if (work_off22 != null) {
            stmt.bindString(47, work_off22);
        }
 
        String work_on23 = entity.getWork_on23();
        if (work_on23 != null) {
            stmt.bindString(48, work_on23);
        }
 
        String work_off23 = entity.getWork_off23();
        if (work_off23 != null) {
            stmt.bindString(49, work_off23);
        }
 
        String work_on24 = entity.getWork_on24();
        if (work_on24 != null) {
            stmt.bindString(50, work_on24);
        }
 
        String work_off24 = entity.getWork_off24();
        if (work_off24 != null) {
            stmt.bindString(51, work_off24);
        }
 
        String work_on25 = entity.getWork_on25();
        if (work_on25 != null) {
            stmt.bindString(52, work_on25);
        }
 
        String work_off25 = entity.getWork_off25();
        if (work_off25 != null) {
            stmt.bindString(53, work_off25);
        }
 
        String work_on26 = entity.getWork_on26();
        if (work_on26 != null) {
            stmt.bindString(54, work_on26);
        }
 
        String work_off26 = entity.getWork_off26();
        if (work_off26 != null) {
            stmt.bindString(55, work_off26);
        }
 
        String work_on27 = entity.getWork_on27();
        if (work_on27 != null) {
            stmt.bindString(56, work_on27);
        }
 
        String work_off27 = entity.getWork_off27();
        if (work_off27 != null) {
            stmt.bindString(57, work_off27);
        }
 
        String work_on28 = entity.getWork_on28();
        if (work_on28 != null) {
            stmt.bindString(58, work_on28);
        }
 
        String work_off28 = entity.getWork_off28();
        if (work_off28 != null) {
            stmt.bindString(59, work_off28);
        }
 
        String work_on29 = entity.getWork_on29();
        if (work_on29 != null) {
            stmt.bindString(60, work_on29);
        }
 
        String work_off29 = entity.getWork_off29();
        if (work_off29 != null) {
            stmt.bindString(61, work_off29);
        }
 
        String work_on30 = entity.getWork_on30();
        if (work_on30 != null) {
            stmt.bindString(62, work_on30);
        }
 
        String work_off30 = entity.getWork_off30();
        if (work_off30 != null) {
            stmt.bindString(63, work_off30);
        }
 
        String work_on31 = entity.getWork_on31();
        if (work_on31 != null) {
            stmt.bindString(64, work_on31);
        }
 
        String work_off31 = entity.getWork_off31();
        if (work_off31 != null) {
            stmt.bindString(65, work_off31);
        }
 
        String mark_all = entity.getMark_all();
        if (mark_all != null) {
            stmt.bindString(66, mark_all);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WorkOnOff entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String id_clerk = entity.getId_clerk();
        if (id_clerk != null) {
            stmt.bindString(3, id_clerk);
        }
 
        String work_on1 = entity.getWork_on1();
        if (work_on1 != null) {
            stmt.bindString(4, work_on1);
        }
 
        String work_off1 = entity.getWork_off1();
        if (work_off1 != null) {
            stmt.bindString(5, work_off1);
        }
 
        String work_on2 = entity.getWork_on2();
        if (work_on2 != null) {
            stmt.bindString(6, work_on2);
        }
 
        String work_off2 = entity.getWork_off2();
        if (work_off2 != null) {
            stmt.bindString(7, work_off2);
        }
 
        String work_on3 = entity.getWork_on3();
        if (work_on3 != null) {
            stmt.bindString(8, work_on3);
        }
 
        String work_off3 = entity.getWork_off3();
        if (work_off3 != null) {
            stmt.bindString(9, work_off3);
        }
 
        String work_on4 = entity.getWork_on4();
        if (work_on4 != null) {
            stmt.bindString(10, work_on4);
        }
 
        String work_off4 = entity.getWork_off4();
        if (work_off4 != null) {
            stmt.bindString(11, work_off4);
        }
 
        String work_on5 = entity.getWork_on5();
        if (work_on5 != null) {
            stmt.bindString(12, work_on5);
        }
 
        String work_off5 = entity.getWork_off5();
        if (work_off5 != null) {
            stmt.bindString(13, work_off5);
        }
 
        String work_on6 = entity.getWork_on6();
        if (work_on6 != null) {
            stmt.bindString(14, work_on6);
        }
 
        String work_off6 = entity.getWork_off6();
        if (work_off6 != null) {
            stmt.bindString(15, work_off6);
        }
 
        String work_on7 = entity.getWork_on7();
        if (work_on7 != null) {
            stmt.bindString(16, work_on7);
        }
 
        String work_off7 = entity.getWork_off7();
        if (work_off7 != null) {
            stmt.bindString(17, work_off7);
        }
 
        String work_on8 = entity.getWork_on8();
        if (work_on8 != null) {
            stmt.bindString(18, work_on8);
        }
 
        String work_off8 = entity.getWork_off8();
        if (work_off8 != null) {
            stmt.bindString(19, work_off8);
        }
 
        String work_on9 = entity.getWork_on9();
        if (work_on9 != null) {
            stmt.bindString(20, work_on9);
        }
 
        String work_off9 = entity.getWork_off9();
        if (work_off9 != null) {
            stmt.bindString(21, work_off9);
        }
 
        String work_on10 = entity.getWork_on10();
        if (work_on10 != null) {
            stmt.bindString(22, work_on10);
        }
 
        String work_off10 = entity.getWork_off10();
        if (work_off10 != null) {
            stmt.bindString(23, work_off10);
        }
 
        String work_on11 = entity.getWork_on11();
        if (work_on11 != null) {
            stmt.bindString(24, work_on11);
        }
 
        String work_off11 = entity.getWork_off11();
        if (work_off11 != null) {
            stmt.bindString(25, work_off11);
        }
 
        String work_on12 = entity.getWork_on12();
        if (work_on12 != null) {
            stmt.bindString(26, work_on12);
        }
 
        String work_off12 = entity.getWork_off12();
        if (work_off12 != null) {
            stmt.bindString(27, work_off12);
        }
 
        String work_on13 = entity.getWork_on13();
        if (work_on13 != null) {
            stmt.bindString(28, work_on13);
        }
 
        String work_off13 = entity.getWork_off13();
        if (work_off13 != null) {
            stmt.bindString(29, work_off13);
        }
 
        String work_on14 = entity.getWork_on14();
        if (work_on14 != null) {
            stmt.bindString(30, work_on14);
        }
 
        String work_off14 = entity.getWork_off14();
        if (work_off14 != null) {
            stmt.bindString(31, work_off14);
        }
 
        String work_on15 = entity.getWork_on15();
        if (work_on15 != null) {
            stmt.bindString(32, work_on15);
        }
 
        String work_off15 = entity.getWork_off15();
        if (work_off15 != null) {
            stmt.bindString(33, work_off15);
        }
 
        String work_on16 = entity.getWork_on16();
        if (work_on16 != null) {
            stmt.bindString(34, work_on16);
        }
 
        String work_off16 = entity.getWork_off16();
        if (work_off16 != null) {
            stmt.bindString(35, work_off16);
        }
 
        String work_on17 = entity.getWork_on17();
        if (work_on17 != null) {
            stmt.bindString(36, work_on17);
        }
 
        String work_off17 = entity.getWork_off17();
        if (work_off17 != null) {
            stmt.bindString(37, work_off17);
        }
 
        String work_on18 = entity.getWork_on18();
        if (work_on18 != null) {
            stmt.bindString(38, work_on18);
        }
 
        String work_off18 = entity.getWork_off18();
        if (work_off18 != null) {
            stmt.bindString(39, work_off18);
        }
 
        String work_on19 = entity.getWork_on19();
        if (work_on19 != null) {
            stmt.bindString(40, work_on19);
        }
 
        String work_off19 = entity.getWork_off19();
        if (work_off19 != null) {
            stmt.bindString(41, work_off19);
        }
 
        String work_on20 = entity.getWork_on20();
        if (work_on20 != null) {
            stmt.bindString(42, work_on20);
        }
 
        String work_off20 = entity.getWork_off20();
        if (work_off20 != null) {
            stmt.bindString(43, work_off20);
        }
 
        String work_on21 = entity.getWork_on21();
        if (work_on21 != null) {
            stmt.bindString(44, work_on21);
        }
 
        String work_off21 = entity.getWork_off21();
        if (work_off21 != null) {
            stmt.bindString(45, work_off21);
        }
 
        String work_on22 = entity.getWork_on22();
        if (work_on22 != null) {
            stmt.bindString(46, work_on22);
        }
 
        String work_off22 = entity.getWork_off22();
        if (work_off22 != null) {
            stmt.bindString(47, work_off22);
        }
 
        String work_on23 = entity.getWork_on23();
        if (work_on23 != null) {
            stmt.bindString(48, work_on23);
        }
 
        String work_off23 = entity.getWork_off23();
        if (work_off23 != null) {
            stmt.bindString(49, work_off23);
        }
 
        String work_on24 = entity.getWork_on24();
        if (work_on24 != null) {
            stmt.bindString(50, work_on24);
        }
 
        String work_off24 = entity.getWork_off24();
        if (work_off24 != null) {
            stmt.bindString(51, work_off24);
        }
 
        String work_on25 = entity.getWork_on25();
        if (work_on25 != null) {
            stmt.bindString(52, work_on25);
        }
 
        String work_off25 = entity.getWork_off25();
        if (work_off25 != null) {
            stmt.bindString(53, work_off25);
        }
 
        String work_on26 = entity.getWork_on26();
        if (work_on26 != null) {
            stmt.bindString(54, work_on26);
        }
 
        String work_off26 = entity.getWork_off26();
        if (work_off26 != null) {
            stmt.bindString(55, work_off26);
        }
 
        String work_on27 = entity.getWork_on27();
        if (work_on27 != null) {
            stmt.bindString(56, work_on27);
        }
 
        String work_off27 = entity.getWork_off27();
        if (work_off27 != null) {
            stmt.bindString(57, work_off27);
        }
 
        String work_on28 = entity.getWork_on28();
        if (work_on28 != null) {
            stmt.bindString(58, work_on28);
        }
 
        String work_off28 = entity.getWork_off28();
        if (work_off28 != null) {
            stmt.bindString(59, work_off28);
        }
 
        String work_on29 = entity.getWork_on29();
        if (work_on29 != null) {
            stmt.bindString(60, work_on29);
        }
 
        String work_off29 = entity.getWork_off29();
        if (work_off29 != null) {
            stmt.bindString(61, work_off29);
        }
 
        String work_on30 = entity.getWork_on30();
        if (work_on30 != null) {
            stmt.bindString(62, work_on30);
        }
 
        String work_off30 = entity.getWork_off30();
        if (work_off30 != null) {
            stmt.bindString(63, work_off30);
        }
 
        String work_on31 = entity.getWork_on31();
        if (work_on31 != null) {
            stmt.bindString(64, work_on31);
        }
 
        String work_off31 = entity.getWork_off31();
        if (work_off31 != null) {
            stmt.bindString(65, work_off31);
        }
 
        String mark_all = entity.getMark_all();
        if (mark_all != null) {
            stmt.bindString(66, mark_all);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public WorkOnOff readEntity(Cursor cursor, int offset) {
        WorkOnOff entity = new WorkOnOff( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // id_clerk
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // work_on1
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // work_off1
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // work_on2
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // work_off2
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // work_on3
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // work_off3
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // work_on4
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // work_off4
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // work_on5
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // work_off5
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // work_on6
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // work_off6
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // work_on7
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // work_off7
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // work_on8
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // work_off8
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // work_on9
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // work_off9
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // work_on10
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // work_off10
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // work_on11
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // work_off11
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // work_on12
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // work_off12
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // work_on13
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // work_off13
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // work_on14
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // work_off14
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // work_on15
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // work_off15
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // work_on16
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // work_off16
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // work_on17
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // work_off17
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // work_on18
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // work_off18
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // work_on19
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // work_off19
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // work_on20
            cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42), // work_off20
            cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // work_on21
            cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // work_off21
            cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // work_on22
            cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46), // work_off22
            cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47), // work_on23
            cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48), // work_off23
            cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49), // work_on24
            cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50), // work_off24
            cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51), // work_on25
            cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52), // work_off25
            cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53), // work_on26
            cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54), // work_off26
            cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55), // work_on27
            cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56), // work_off27
            cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57), // work_on28
            cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58), // work_off28
            cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59), // work_on29
            cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60), // work_off29
            cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61), // work_on30
            cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62), // work_off30
            cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63), // work_on31
            cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64), // work_off31
            cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65) // mark_all
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WorkOnOff entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setId_clerk(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setWork_on1(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setWork_off1(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setWork_on2(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setWork_off2(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setWork_on3(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setWork_off3(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setWork_on4(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setWork_off4(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setWork_on5(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setWork_off5(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setWork_on6(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setWork_off6(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setWork_on7(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setWork_off7(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setWork_on8(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setWork_off8(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setWork_on9(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setWork_off9(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setWork_on10(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setWork_off10(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setWork_on11(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setWork_off11(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setWork_on12(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setWork_off12(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setWork_on13(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setWork_off13(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setWork_on14(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setWork_off14(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setWork_on15(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setWork_off15(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setWork_on16(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setWork_off16(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setWork_on17(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setWork_off17(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setWork_on18(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setWork_off18(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setWork_on19(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setWork_off19(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setWork_on20(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setWork_off20(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
        entity.setWork_on21(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setWork_off21(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setWork_on22(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setWork_off22(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setWork_on23(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
        entity.setWork_off23(cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48));
        entity.setWork_on24(cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49));
        entity.setWork_off24(cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50));
        entity.setWork_on25(cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51));
        entity.setWork_off25(cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52));
        entity.setWork_on26(cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53));
        entity.setWork_off26(cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54));
        entity.setWork_on27(cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55));
        entity.setWork_off27(cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56));
        entity.setWork_on28(cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57));
        entity.setWork_off28(cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58));
        entity.setWork_on29(cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59));
        entity.setWork_off29(cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60));
        entity.setWork_on30(cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61));
        entity.setWork_off30(cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62));
        entity.setWork_on31(cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63));
        entity.setWork_off31(cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64));
        entity.setMark_all(cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65));
     }
    
    @Override
    protected final String updateKeyAfterInsert(WorkOnOff entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(WorkOnOff entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WorkOnOff entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
